export enum AstChars {
	Whitespace = ' ',
	Tab = '\t',
	NewLine = '\n',
	// CarriageReturn = '\r',
	WellNumber = '#',
	At = '@',
	// Exclamation = '!',
	Backslash = '\\',
	// Asterisk = '*',
	Semicolon = ';',
	Colon = ':',
	Dot = '.',
	Comma = ',',
	LBrace = '{',
	RBrace = '}',
	LBrack = '[',
	RBrack = ']',
	LParen = '(',
	RParen = ')',
}
