export enum AstLiterals {
	TRUE = 'true',
	FALSE = 'false',
	BinaryStartMark = '0b',
	HexadecimalStartMark = '0x',
	StringQuotationMark = '\'',
	StringQuotationMarkML = '\'\'\'',
	StringBackspaceEscape = '\\b',
	StringFormFeedEscape = '\\f',
	StringNewLineEscape = '\\n',
	StringCarriageReturnEscape = '\\r',
	StringSingleSpaceEscape = '\\s',
	StringTabulationEscape = '\\t',
	StringBackslashEscape = '\\\\',
	StringSingleQuoteEscape = '\\\'',
	StringDoubleQuoteEscape = '\\"',
	StringDollarEscape = '\\$',
	StringUnicodeEscapeMark = '\\u',
	GStringQuotationMark = '"',
	GStringQuotationMarkML = '"""',
	SlashyGStringQuotationMark = '/',
	DollarSlashyGStringQuotationStartMark = '$/',
	DollarSlashyGStringQuotationEndMark = '/$',
	SlashyGStringBackslashEscape = '\\/',
	DollarSlashyGStringDollarEscape = '$$',
	GStringInterpolationSymbol = '$',
	RegexpPatternStartMark = '~/',
}
