export enum AstLiterals {
	TRUE = 'true',
	FALSE = 'false',
	StringQuotationMark = '\'',
	StringQuotationMarkML = '\'\'\'',
	StringBackspaceEscape = '\\b',
	StringFormFeedEscape = '\\f',
	StringNewlineEscape = '\\n',
	StringCarriageReturnEscape = '\\r',
	StringSingleSpaceEscape = '\\s',
	StringTabulationEscape = '\\t',
	StringBackslashEscape = '\\\\',
	StringSingleQuoteEscape = '\\\'',
	StringDoubleQuoteEscape = '\\"',
	StringDollarEscape = '\\$',
	StringUnicodeEscapeMark = '\\u',
	GStringQuotationMark = '"',
	GStringQuotationMarkML = '"""',
	SlashyGStringQuotationMark = '/',
	DollarSlashyGStringQuotationStartMark = '$/',
	DollarSlashyGStringQuotationEndMark = '/$',
	SlashyGStringSlashEscape = '\\/',
	DollarSlashyGStringDollarEscape = '$$',
	GStringInterpolationStartMark = '$',
	GStringInterpolationLBraceStartMark = `\${`,
	GStringInterpolationRBraceEndMark = '}',
	RegexpPatternStartMark = '~/',
}
