import {AstNode} from './ast-node';
import {
	AbstractNode,
	AddAssignNode,
	AddNode,
	AndAssignNode,
	AndNode,
	AnnotationDeclarationNode,
	ArrowNode,
	AsNode,
	AssertNode,
	AssignNode,
	AtInterfaceDeclarationNode,
	AtInterfaceNode,
	BinaryLiteralNode,
	BinaryStartMarkNode,
	BitandNode,
	BitnotNode,
	BitorNode,
	BooleanLiteralNode,
	BooleanNode,
	BreakNode,
	ByteNode,
	CaseNode,
	CatchNode,
	CharLiteralNode,
	CharNode,
	CharsNode,
	ClassDeclarationNode,
	ClassNode,
	ColonNode,
	CommaNode,
	CommentKeywordNode,
	CompilationUnitNode,
	ConstNode,
	ContinueNode,
	DecimalExponentPartNode,
	DecimalExponentSymbolNode,
	DecimalLiteralNode,
	DecreaseNode,
	DefaultNode,
	DefNode,
	DivideAssignNode,
	DivideNode,
	DollarSlashyGStringDollarEscapeNode,
	DollarSlashyGStringLiteralNode,
	DollarSlashyGStringQuotationMarkBeginNode,
	DollarSlashyGStringQuotationMarkEndNode,
	DollarSlashyGStringSlashEscapeNode,
	DoNode,
	DotNode,
	DoubleNode,
	EllipsisNode,
	ElseNode,
	ElvisAssignNode,
	ElvisNode,
	EnumClassDeclarationNode,
	EnumNode,
	EqualNode,
	ExtendsNode,
	FinallyNode,
	FinalNode,
	FloatNode,
	ForNode,
	GotoNode,
	GreaterThanNode,
	GreaterThanOrEqualNode,
	GStringContentNode,
	GStringInterpolationContentNode,
	GStringInterpolationNode,
	GStringInterpolationSymbolNode,
	GStringLiteralNode,
	GStringQuotationMarkMLNode,
	GStringQuotationMarkNode,
	HexadecimalLiteralNode,
	HexadecimalStartMarkNode,
	IdenticalNode,
	IdentifierNode,
	IfNode,
	ImplementsNode,
	ImportDeclarationNode,
	ImportNode,
	IncreaseNode,
	InNode,
	InstanceofNode,
	IntegralLiteralNode,
	InterfaceDeclarationNode,
	InterfaceNode,
	IntNode,
	LBraceNode,
	LBrackNode,
	LessThanNode,
	LessThanOrEqualNode,
	LongNode,
	LParenNode,
	LshiftAssignNode,
	MethodPointerNode,
	MethodReferenceNode,
	ModAssignNode,
	ModNode,
	MultipleAssignNode,
	MultipleLinesCommentEndMarkNode,
	MultipleLinesCommentNode,
	MultipleLinesCommentStartMarkNode,
	MultipleNode,
	NativeNode,
	NewLineNode,
	NewNode,
	NonSealedNode,
	NotEqualNode,
	NotIdenticalNode,
	NotInNode,
	NotInstanceOfNode,
	NotNode,
	NullNode,
	NumericBasePartNode,
	NumericSignPartNode,
	NumericSuffixPartNode,
	NumericUnderscorePartNode,
	OctalLiteralNode,
	OctalStartMarkNode,
	OrAssignNode,
	OrNode,
	PackageDeclarationNode,
	PackageNode,
	PermitsNode,
	PowerAssignNode,
	PowerNode,
	PrivateNode,
	ProtectedNode,
	PublicNode,
	QuestionNode,
	RangeExclusiveFullNode,
	RangeExclusiveLeftNode,
	RangeExclusiveRightNode,
	RangeInclusiveNode,
	RBraceNode,
	RBrackNode,
	RecordClassDeclarationNode,
	RecordNode,
	RegexFindNode,
	RegexMatchNode,
	ReturnNode,
	RParenNode,
	RshiftAssignNode,
	SafeChainDotNode,
	SafeDotNode,
	SafeIndexCloseNode,
	SafeIndexNode,
	ScriptCommandNode,
	ScriptCommandStartMarkNode,
	SealedNode,
	SemicolonNode,
	ShortNode,
	SingleLineCommentNode,
	SingleLineCommentStartMarkNode,
	SlashyGStringBackslashEscapeNode,
	SlashyGStringLiteralNode,
	SlashyGStringQuotationMarkNode,
	SpaceshipNode,
	SpreadDotNode,
	StaticNode,
	StrictfpNode,
	StringBackslashEscapeNode,
	StringBackspaceEscapeNode,
	StringCarriageReturnEscapeNode,
	StringDollarEscapeNode,
	StringDoubleQuoteEscapeNode,
	StringFormFeedEscapeNode,
	StringLiteralNode,
	StringMLFirstNewLineEraserNode,
	StringNewLineEscapeNode,
	StringQuotationMarkMLNode,
	StringQuotationMarkNode,
	StringSingleQuoteEscapeNode,
	StringSingleSpaceEscapeNode,
	StringTabulationEscapeNode,
	StringUnicodeEscapeContentNode,
	StringUnicodeEscapeMarkNode,
	StringUnicodeEscapeNode,
	SubtractAssignNode,
	SubtractNode,
	SuperNode,
	SwitchNode,
	SynchronizedNode,
	TabsNode,
	ThisNode,
	ThreadsafeNode,
	ThrowNode,
	ThrowsNode,
	TraitClassDeclarationNode,
	TraitNode,
	TransientNode,
	TryNode,
	UndeterminedCharsNode,
	UnexpectedCharsNode,
	UrshiftAssignNode,
	VarNode,
	VoidNode,
	VolatileNode,
	WhileNode,
	WhitespacesNode,
	XorAssignNode,
	XorNode,
	YieldNode
} from './node';
import {TokenId} from './tokens';
import {
	ArrowCaptor,
	AstNodeCaptor,
	AstVisitor,
	AtInterfaceDeclarationCaptor,
	ClassDeclarationCaptor,
	CommaCaptor,
	DotCaptor,
	ElvisCaptor,
	EnumClassDeclarationCaptor,
	IdenticalCaptor,
	IdentifierCaptor,
	ImportDeclarationCaptor,
	InterfaceDeclarationCaptor,
	KwAbstractCaptor,
	KwAsCaptor,
	KwConstCaptor,
	KwDefaultCaptor,
	KwExtendsCaptor,
	KwGotoCaptor,
	KwImplementsCaptor,
	KwNativeCaptor,
	KwNonSealedCaptor,
	KwPermitsCaptor,
	KwPrivateCaptor,
	KwProtectedCaptor,
	KwPublicCaptor,
	KwSealedCaptor,
	KwStaticCaptor,
	KwStrictfpCaptor,
	KwSynchronizedCaptor,
	KwVolatileCaptor,
	LBraceCaptor,
	LBrackCaptor,
	LParenCaptor,
	MethodPointerCaptor,
	MethodReferenceCaptor,
	MultipleLinesCommentCaptor,
	NewLineStartsWithCarriageReturnCaptor,
	NewLineStartsWithNewLineCaptor,
	NotIdenticalCaptor,
	PackageDeclarationCaptor,
	PowerAssignCaptor,
	PowerCaptor,
	RangeExclusiveFullCaptor,
	RangeExclusiveLeftCaptor,
	RangeExclusiveRightCaptor,
	RangeInclusiveCaptor,
	RBraceCaptor,
	RBrackCaptor,
	RecordClassDeclarationCaptor,
	RegexFindCaptor,
	RegexMatchCaptor,
	RParenCaptor,
	SafeChainDotCaptor,
	SafeDotCaptor,
	SafeIndexCaptor,
	SafeIndexCloseCaptor,
	ScriptCommandCaptor,
	SemicolonCaptor,
	SingleLineCommentCaptor,
	SpaceshipCaptor,
	SpreadDotCaptor,
	TabsCaptor,
	TraitClassDeclarationCaptor,
	UndeterminedCharsCaptor,
	WhitespacesCaptor
} from './visit';

// constructor of elements
type ClassImplementsAstNode = new (...args: any[]) => AstNode;
type ClassImplementsAstNodeCaptor = new (astVisitor: AstVisitor) => AstNodeCaptor;

type CompilationUnitTokenId = TokenId.COMPILATION_UNIT;
type ScriptCommandMarkTokenId = TokenId.ScriptCommandStartMark;
type CommentTokenIds =
	| TokenId.SingleLineCommentStartMark
	| TokenId.MultipleLinesCommentStartMark
	| TokenId.MultipleLinesCommentEndMark
	| TokenId.CommentKeyword;
type PackageNoCaptorTokenId = TokenId.PACKAGE;
type ImportNoCaptorTokenId = TokenId.IMPORT
type TypeTokenIds =
	| TokenId.INTERFACE
	| TokenId.CLASS
	| TokenId.AT_INTERFACE
	| TokenId.ENUM
	| TokenId.RECORD
	| TokenId.TRAIT;
type CharsNoCaptorTokenId = TokenId.Chars | TokenId.UnexpectedChars;
type NoCaptorTokenIds =
	| CompilationUnitTokenId
	| ScriptCommandMarkTokenId
	| CommentTokenIds
	| PackageNoCaptorTokenId | ImportNoCaptorTokenId
	| TypeTokenIds
	| CharsNoCaptorTokenId;

type SpecialDefTokenIds = TokenId.NewLine;
type CaptorNotDefinedYetTokenIds = TokenId.AnnotationDeclaration;
type StandardDefTokenIds = Exclude<TokenId, NoCaptorTokenIds | SpecialDefTokenIds | CaptorNotDefinedYetTokenIds>;
type TokenAstDefsType = {
	[key in StandardDefTokenIds]: [ClassImplementsAstNode, ClassImplementsAstNodeCaptor] | [ClassImplementsAstNode]
} & {
	[key in NoCaptorTokenIds]: [ClassImplementsAstNode]
} & {
	[key in TokenId.NewLine]: [ClassImplementsAstNode, ClassImplementsAstNodeCaptor, ClassImplementsAstNodeCaptor]
} & {
	[key in CaptorNotDefinedYetTokenIds]: [ClassImplementsAstNode]
}

/**
 * list all token ids, nodes and captors
 */
export const TokenAstDefs: TokenAstDefsType = {
	[TokenId.COMPILATION_UNIT]: [CompilationUnitNode],
	// primitive types
	[TokenId.BOOLEAN]: [BooleanNode],
	[TokenId.CHAR]: [CharNode],
	[TokenId.BYTE]: [ByteNode],
	[TokenId.SHORT]: [ShortNode],
	[TokenId.INT]: [IntNode],
	[TokenId.LONG]: [LongNode],
	[TokenId.FLOAT]: [FloatNode],
	[TokenId.DOUBLE]: [DoubleNode],
	// groovy keywords
	[TokenId.AS]: [AsNode, KwAsCaptor],
	[TokenId.DEF]: [DefNode],
	[TokenId.IN]: [InNode],
	[TokenId.TRAIT]: [TraitNode],
	[TokenId.THREADSAFE]: [ThreadsafeNode],
	// java keywords
	[TokenId.ABSTRACT]: [AbstractNode, KwAbstractCaptor],
	[TokenId.ASSERT]: [AssertNode],
	[TokenId.AT_INTERFACE]: [AtInterfaceNode],
	[TokenId.BREAK]: [BreakNode],
	[TokenId.CASE]: [CaseNode],
	[TokenId.CATCH]: [CatchNode],
	[TokenId.CLASS]: [ClassNode],
	[TokenId.CONST]: [ConstNode, KwConstCaptor],
	[TokenId.CONTINUE]: [ContinueNode],
	[TokenId.DEFAULT]: [DefaultNode, KwDefaultCaptor],
	[TokenId.DO]: [DoNode],
	[TokenId.ELSE]: [ElseNode],
	[TokenId.ENUM]: [EnumNode],
	[TokenId.EXTENDS]: [ExtendsNode, KwExtendsCaptor],
	[TokenId.FINAL]: [FinalNode],
	[TokenId.FINALLY]: [FinallyNode],
	[TokenId.FOR]: [ForNode],
	[TokenId.GOTO]: [GotoNode, KwGotoCaptor],
	[TokenId.IF]: [IfNode],
	[TokenId.IMPLEMENTS]: [ImplementsNode, KwImplementsCaptor],
	[TokenId.IMPORT]: [ImportNode],
	[TokenId.INSTANCEOF]: [InstanceofNode],
	[TokenId.INTERFACE]: [InterfaceNode],
	[TokenId.NATIVE]: [NativeNode, KwNativeCaptor],
	[TokenId.NEW]: [NewNode],
	[TokenId.NON_SEALED]: [NonSealedNode, KwNonSealedCaptor],
	[TokenId.NULL]: [NullNode],
	[TokenId.PACKAGE]: [PackageNode],
	[TokenId.PERMITS]: [PermitsNode, KwPermitsCaptor],
	[TokenId.PRIVATE]: [PrivateNode, KwPrivateCaptor],
	[TokenId.PROTECTED]: [ProtectedNode, KwProtectedCaptor],
	[TokenId.PUBLIC]: [PublicNode, KwPublicCaptor],
	[TokenId.RECORD]: [RecordNode],
	[TokenId.RETURN]: [ReturnNode],
	[TokenId.SEALED]: [SealedNode, KwSealedCaptor],
	[TokenId.STATIC]: [StaticNode, KwStaticCaptor],
	[TokenId.STRICTFP]: [StrictfpNode, KwStrictfpCaptor],
	[TokenId.SUPER]: [SuperNode],
	[TokenId.SWITCH]: [SwitchNode],
	[TokenId.SYNCHRONIZED]: [SynchronizedNode, KwSynchronizedCaptor],
	[TokenId.THIS]: [ThisNode],
	[TokenId.THROW]: [ThrowNode],
	[TokenId.THROWS]: [ThrowsNode],
	[TokenId.TRANSIENT]: [TransientNode],
	[TokenId.TRY]: [TryNode],
	[TokenId.VAR]: [VarNode],
	[TokenId.VOID]: [VoidNode],
	[TokenId.VOLATILE]: [VolatileNode, KwVolatileCaptor],
	[TokenId.WHILE]: [WhileNode],
	[TokenId.YIELD]: [YieldNode],
	// boolean
	[TokenId.BooleanLiteral]: [BooleanLiteralNode],
	// numeric
	[TokenId.NumericSignPart]: [NumericSignPartNode],
	[TokenId.NumericBasePart]: [NumericBasePartNode],
	[TokenId.NumericUnderscorePart]: [NumericUnderscorePartNode],
	[TokenId.NumericSuffixPart]: [NumericSuffixPartNode],
	[TokenId.BinaryStartMark]: [BinaryStartMarkNode],
	[TokenId.BinaryLiteral]: [BinaryLiteralNode],
	[TokenId.OctalStartMark]: [OctalStartMarkNode],
	[TokenId.OctalLiteral]: [OctalLiteralNode],
	[TokenId.HexadecimalStartMark]: [HexadecimalStartMarkNode],
	[TokenId.HexadecimalLiteral]: [HexadecimalLiteralNode],
	[TokenId.IntegralLiteral]: [IntegralLiteralNode],
	[TokenId.DecimalExponentSymbol]: [DecimalExponentSymbolNode],
	[TokenId.DecimalExponentPart]: [DecimalExponentPartNode],
	[TokenId.DecimalLiteral]: [DecimalLiteralNode],
	// char
	[TokenId.CharLiteral]: [CharLiteralNode],
	// string and gstring
	[TokenId.StringQuotationMark]: [StringQuotationMarkNode],
	[TokenId.StringQuotationMarkML]: [StringQuotationMarkMLNode],
	[TokenId.StringMLFirstNewLineEraser]: [StringMLFirstNewLineEraserNode],
	[TokenId.StringBackspaceEscape]: [StringBackspaceEscapeNode],
	[TokenId.StringFormFeedEscape]: [StringFormFeedEscapeNode],
	[TokenId.StringNewLineEscape]: [StringNewLineEscapeNode],
	[TokenId.StringCarriageReturnEscape]: [StringCarriageReturnEscapeNode],
	[TokenId.StringSingleSpaceEscape]: [StringSingleSpaceEscapeNode],
	[TokenId.StringTabulationEscape]: [StringTabulationEscapeNode],
	[TokenId.StringBackslashEscape]: [StringBackslashEscapeNode],
	[TokenId.StringSingleQuoteEscape]: [StringSingleQuoteEscapeNode],
	[TokenId.StringDoubleQuoteEscape]: [StringDoubleQuoteEscapeNode],
	[TokenId.StringDollarEscape]: [StringDollarEscapeNode],
	[TokenId.StringUnicodeEscape]: [StringUnicodeEscapeNode],
	[TokenId.StringUnicodeEscapeMark]: [StringUnicodeEscapeMarkNode],
	[TokenId.StringUnicodeEscapeContent]: [StringUnicodeEscapeContentNode],
	[TokenId.StringLiteral]: [StringLiteralNode],
	[TokenId.GStringQuotationMark]: [GStringQuotationMarkNode],
	[TokenId.GStringQuotationMarkML]: [GStringQuotationMarkMLNode],
	[TokenId.SlashyGStringQuotationMark]: [SlashyGStringQuotationMarkNode],
	[TokenId.DollarSlashyGStringQuotationMarkBegin]: [DollarSlashyGStringQuotationMarkBeginNode],
	[TokenId.DollarSlashyGStringQuotationMarkEnd]: [DollarSlashyGStringQuotationMarkEndNode],
	[TokenId.SlashyGStringBackslashEscape]: [SlashyGStringBackslashEscapeNode],
	[TokenId.DollarSlashyGStringDollarEscape]: [DollarSlashyGStringDollarEscapeNode],
	[TokenId.DollarSlashyGStringSlashEscape]: [DollarSlashyGStringSlashEscapeNode],
	[TokenId.GStringContent]: [GStringContentNode],
	[TokenId.GStringInterpolationSymbol]: [GStringInterpolationSymbolNode],
	[TokenId.GStringInterpolationContent]: [GStringInterpolationContentNode],
	[TokenId.GStringInterpolation]: [GStringInterpolationNode],
	[TokenId.GStringLiteral]: [GStringLiteralNode],
	[TokenId.SlashyGStringLiteral]: [SlashyGStringLiteralNode],
	[TokenId.DollarSlashyGStringLiteral]: [DollarSlashyGStringLiteralNode],
	// Groovy Operators
	[TokenId.RangeInclusive]: [RangeInclusiveNode, RangeInclusiveCaptor],
	[TokenId.RangeExclusiveLeft]: [RangeExclusiveLeftNode, RangeExclusiveLeftCaptor],
	[TokenId.RangeExclusiveRight]: [RangeExclusiveRightNode, RangeExclusiveRightCaptor],
	[TokenId.RangeExclusiveFull]: [RangeExclusiveFullNode, RangeExclusiveFullCaptor],
	[TokenId.SpreadDot]: [SpreadDotNode, SpreadDotCaptor],
	[TokenId.SafeDot]: [SafeDotNode, SafeDotCaptor],
	[TokenId.SafeIndex]: [SafeIndexNode, SafeIndexCaptor],
	[TokenId.SafeIndexClose]: [SafeIndexCloseNode, SafeIndexCloseCaptor],
	[TokenId.SafeChainDot]: [SafeChainDotNode, SafeChainDotCaptor],
	[TokenId.Elvis]: [ElvisNode, ElvisCaptor],
	[TokenId.MethodPointer]: [MethodPointerNode, MethodPointerCaptor],
	[TokenId.MethodReference]: [MethodReferenceNode, MethodReferenceCaptor],
	[TokenId.RegexFind]: [RegexFindNode, RegexFindCaptor],
	[TokenId.RegexMatch]: [RegexMatchNode, RegexMatchCaptor],
	[TokenId.Power]: [PowerNode, PowerCaptor],
	[TokenId.PowerAssign]: [PowerAssignNode, PowerAssignCaptor],
	[TokenId.Spaceship]: [SpaceshipNode, SpaceshipCaptor],
	[TokenId.Identical]: [IdenticalNode, IdenticalCaptor],
	[TokenId.NotIdentical]: [NotIdenticalNode, NotIdenticalCaptor],
	[TokenId.Arrow]: [ArrowNode, ArrowCaptor],
	[TokenId.NotInstanceOf]: [NotInstanceOfNode],
	[TokenId.NotIn]: [NotInNode],
	// separators
	[TokenId.LBrace]: [LBraceNode, LBraceCaptor],
	[TokenId.RBrace]: [RBraceNode, RBraceCaptor],
	[TokenId.LParen]: [LParenNode, LParenCaptor],
	[TokenId.RParen]: [RParenNode, RParenCaptor],
	[TokenId.LBrack]: [LBrackNode, LBrackCaptor],
	[TokenId.RBrack]: [RBrackNode, RBrackCaptor],
	[TokenId.Semicolon]: [SemicolonNode, SemicolonCaptor],
	[TokenId.Comma]: [CommaNode, CommaCaptor],
	[TokenId.Dot]: [DotNode, DotCaptor],
	// operators
	[TokenId.Assign]: [AssignNode],
	[TokenId.GreaterThan]: [GreaterThanNode],
	[TokenId.LessThan]: [LessThanNode],
	[TokenId.Not]: [NotNode],
	[TokenId.Bitnot]: [BitnotNode],
	[TokenId.Question]: [QuestionNode],
	[TokenId.Colon]: [ColonNode],
	[TokenId.Equal]: [EqualNode],
	[TokenId.LessThanOrEqual]: [LessThanOrEqualNode],
	[TokenId.GreaterThanOrEqual]: [GreaterThanOrEqualNode],
	[TokenId.NotEqual]: [NotEqualNode],
	[TokenId.And]: [AndNode],
	[TokenId.Or]: [OrNode],
	[TokenId.Increase]: [IncreaseNode],
	[TokenId.Decrease]: [DecreaseNode],
	[TokenId.Add]: [AddNode],
	[TokenId.Subtract]: [SubtractNode],
	[TokenId.Multiple]: [MultipleNode],
	[TokenId.Divide]: [DivideNode],
	[TokenId.Bitand]: [BitandNode],
	[TokenId.Bitor]: [BitorNode],
	[TokenId.Xor]: [XorNode],
	[TokenId.Mod]: [ModNode],
	[TokenId.AddAssign]: [AddAssignNode],
	[TokenId.SubtractAssign]: [SubtractAssignNode],
	[TokenId.MultipleAssign]: [MultipleAssignNode],
	[TokenId.DivideAssign]: [DivideAssignNode],
	[TokenId.AndAssign]: [AndAssignNode],
	[TokenId.OrAssign]: [OrAssignNode],
	[TokenId.XorAssign]: [XorAssignNode],
	[TokenId.ModAssign]: [ModAssignNode],
	[TokenId.LshiftAssign]: [LshiftAssignNode],
	[TokenId.RshiftAssign]: [RshiftAssignNode],
	[TokenId.UrshiftAssign]: [UrshiftAssignNode],
	[TokenId.ElvisAssign]: [ElvisAssignNode],
	[TokenId.Ellipsis]: [EllipsisNode],
	// comment
	[TokenId.CommentKeyword]: [CommentKeywordNode],
	[TokenId.SingleLineCommentStartMark]: [SingleLineCommentStartMarkNode],
	[TokenId.SingleLineComment]: [SingleLineCommentNode, SingleLineCommentCaptor],
	[TokenId.MultipleLinesCommentStartMark]: [MultipleLinesCommentStartMarkNode],
	[TokenId.MultipleLinesCommentEndMark]: [MultipleLinesCommentEndMarkNode],
	[TokenId.MultipleLinesComment]: [MultipleLinesCommentNode, MultipleLinesCommentCaptor],
	// shebang command
	[TokenId.ScriptCommandStartMark]: [ScriptCommandStartMarkNode],
	[TokenId.ScriptCommand]: [ScriptCommandNode, ScriptCommandCaptor],
	// text content
	[TokenId.Whitespaces]: [WhitespacesNode, WhitespacesCaptor],
	[TokenId.Tabs]: [TabsNode, TabsCaptor],
	[TokenId.NewLine]: [NewLineNode, NewLineStartsWithNewLineCaptor, NewLineStartsWithCarriageReturnCaptor],
	[TokenId.Chars]: [CharsNode],
	[TokenId.Identifier]: [IdentifierNode, IdentifierCaptor],
	[TokenId.UndeterminedChars]: [UndeterminedCharsNode, UndeterminedCharsCaptor],
	[TokenId.UnexpectedChars]: [UnexpectedCharsNode],
	// statements
	[TokenId.PackageDeclaration]: [PackageDeclarationNode, PackageDeclarationCaptor],
	[TokenId.ImportDeclaration]: [ImportDeclarationNode, ImportDeclarationCaptor],
	[TokenId.InterfaceDeclaration]: [InterfaceDeclarationNode, InterfaceDeclarationCaptor],
	[TokenId.ClassDeclaration]: [ClassDeclarationNode, ClassDeclarationCaptor],
	[TokenId.AtInterfaceClassDeclaration]: [AtInterfaceDeclarationNode, AtInterfaceDeclarationCaptor],
	[TokenId.EnumClassDeclaration]: [EnumClassDeclarationNode, EnumClassDeclarationCaptor],
	[TokenId.RecordClassDeclaration]: [RecordClassDeclarationNode, RecordClassDeclarationCaptor],
	[TokenId.TraitClassDeclaration]: [TraitClassDeclarationNode, TraitClassDeclarationCaptor],
	[TokenId.AnnotationDeclaration]: [AnnotationDeclarationNode]
} as const;